name: charge_wallet_sdk
description: SDK for Charge Wallet API
version: 0.0.2+6
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  decimal: ^2.3.2
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  gql: ^0.14.0
  graphql: ^5.1.1
  hex: ^0.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  path: ^1.8.2
  retrofit: ^3.3.1
  web3dart:
         path: ../web3dart
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
